### ISSUE TITLE
Several ones not working

### ISSUE THREAD

**Issue by finativethefreak** [Kokaiinum/MobReplacer#1]
Upon testing idol_class_a, idol_class_b, idol_class_c, idol_class_d don't seem to be working.

**Comment by finativethefreak** [comment]
Btw they are supposed to replace the four classmates models in the 6th cut-scene for Himekawa Mai.
Everything else is working accordingly.

**Comment by J4m353y** [comment]
I have also found this bug, please fix.
Amazing mod btw!

**Comment by dstw98** [comment]
Also encountered this issue, pls fix. Otherwise great mod!

**Comment by Kokaiinum** [comment]
Should be fixed now. Very easy fix, embarrassing this problem existed in the first place. Thank you for the report (sorry it took me 3 months to read it)
